const ROOTS=["C","C#","D","Eb","E","F","F#","G","Ab","A","Bb","B"];
const QUALITIES=["","6","7","9","maj7","m","m6","m7","m9","sus2","sus4","+","dim"];
const CHARANGO_CHORDS={G:{name:"Sol mayor",tones:["G","B","D"],fingers:[[1,2,2],[2,3,3],[3,1,1],[4,2,4]],open:[5]},D:{name:"Re mayor",tones:["D","F#","A"],fingers:[[1,2,1],[2,3,3],[3,2,2]],open:[4,5]},Em:{name:"Mi menor",tones:["E","G","B"],fingers:[[2,2,2],[3,2,3]],open:[1,4,5]},C:{name:"Do mayor",tones:["C","E","G"],fingers:[[2,1,1],[4,2,2]],open:[1,3,5]},Am:{name:"La menor",tones:["A","C","E"],fingers:[[2,1,1],[3,2,2]],open:[1,4,5]}};
const state={root:"G",selectedChord:"G",section:"intro",sequences:{intro:[],verso:[],coro:[],puente:[]},notes:{intro:"",verso:"",coro:"",puente:""},strum:"↓ ↓↑ ↑↓↑",strumNotes:"",status:"En aprendizaje",key:"G"};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function renderRootButtons(){const el=$("#rootButtons");el.replaceChildren();ROOTS.forEach(root=>{const b=document.createElement("button");b.textContent=root;b.classList.toggle("active",root===state.root);b.addEventListener("click",()=>{state.root=root;$("#familyTitle").textContent=root;renderRootButtons();renderQualityButtons()});el.append(b)})}
function renderQualityButtons(){const el=$("#qualityButtons");el.replaceChildren();QUALITIES.forEach(s=>{const chord=state.root+s;const b=document.createElement("button");b.textContent=chord;b.classList.toggle("active",chord===state.selectedChord);b.addEventListener("click",()=>{selectChord(chord);addChord(chord)});el.append(b)})}
function selectChord(chord){state.selectedChord=chord;renderQualityButtons();renderChordDetail()}
function addChord(chord){state.sequences[state.section].push(chord);renderSequence();renderUsedChords();markDirty()}
function renderSequence(){const el=$("#sequence"),arr=state.sequences[state.section];el.replaceChildren();el.classList.toggle("empty",!arr.length);arr.forEach((chord,i)=>{const b=document.createElement("button");b.className="chord-chip";b.textContent=chord;b.addEventListener("click",()=>selectChord(chord));b.addEventListener("dblclick",()=>{arr.splice(i,1);renderSequence();renderUsedChords();markDirty()});el.append(b)})}
function renderUsedChords(){const el=$("#usedChords"),unique=[...new Set(Object.values(state.sequences).flat())];el.replaceChildren();if(!unique.length){el.textContent="Todavía no has registrado acordes.";return}unique.forEach(chord=>{const b=document.createElement("button");b.className="chord-chip";b.textContent=chord;b.addEventListener("click",()=>selectChord(chord));el.append(b)})}
function renderChordDetail(){const chord=state.selectedChord,data=CHARANGO_CHORDS[chord];$("#selectedChordLabel").textContent=chord;$("#selectedChordName").textContent=data?data.name:"Digitación por completar";$("#chordTones").textContent=data?data.tones.join(" · "):"—";renderFretboard(data)}
function renderFretboard(data){const el=$("#fretboard");el.replaceChildren();for(let s=1;s<=5;s++){const l=document.createElement("span");l.className="string-label";l.textContent=`${s}ª`;l.style.top=`${(s-.5)*20}%`;el.append(l)}if(!data)return;(data.open||[]).forEach(string=>{const d=document.createElement("span");d.className="open-string";d.style.left="5%";d.style.top=`${(string-.5)*20}%`;el.append(d)});data.fingers.forEach(([string,fret,finger])=>{const d=document.createElement("span");d.className="finger-dot";d.textContent=finger;d.style.left=`${((fret-.5)/6)*100}%`;d.style.top=`${(string-.5)*20}%`;el.append(d)})}
function freq(note){const m={C:0,"C#":1,D:2,Eb:3,E:4,F:5,"F#":6,G:7,Ab:8,A:9,Bb:10,B:11};return 440*Math.pow(2,((60+(m[note]??0))-69)/12)}
function synthChord(chord){const data=CHARANGO_CHORDS[chord];if(!data){$("#saveStatus").textContent=`Aún falta registrar la digitación/sonido de ${chord}.`;return}const ctx=new (window.AudioContext||window.webkitAudioContext)(),now=ctx.currentTime;data.tones.forEach((note,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type="triangle";o.frequency.value=freq(note);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.11,now+.02+i*.012);g.gain.exponentialRampToValueAtTime(.0001,now+1.2);o.connect(g).connect(ctx.destination);o.start(now+i*.025);o.stop(now+1.25)})}
function markDirty(){$("#saveStatus").textContent="Cambios sin guardar"}
$$('#sectionTabs button').forEach(btn=>btn.addEventListener('click',()=>{state.notes[state.section]=$("#sectionNotes").value;state.section=btn.dataset.section;$$('#sectionTabs button').forEach(x=>x.classList.toggle('active',x===btn));$("#sectionNotes").value=state.notes[state.section];renderSequence()}));
$("#undoChordBtn").addEventListener("click",()=>{state.sequences[state.section].pop();renderSequence();renderUsedChords();markDirty()});$("#clearChordBtn").addEventListener("click",()=>{state.sequences[state.section]=[];renderSequence();renderUsedChords();markDirty()});$("#sectionNotes").addEventListener("input",e=>{state.notes[state.section]=e.target.value;markDirty()});
$$('#strumOptions button').forEach(btn=>btn.addEventListener('click',()=>{$$('#strumOptions button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');state.strum=btn.dataset.pattern;markDirty()}));$("#strumNotes").addEventListener("input",e=>{state.strumNotes=e.target.value;markDirty()});
$("#playChordBtn").addEventListener("click",()=>synthChord(state.selectedChord));$("#earPlayBtn").addEventListener("click",()=>synthChord(state.selectedChord));
function qIndex(){return QUALITIES.findIndex(s=>state.root+s===state.selectedChord)}$("#prevChordBtn").addEventListener("click",()=>{let i=qIndex();if(i<0)i=0;i=(i-1+QUALITIES.length)%QUALITIES.length;selectChord(state.root+QUALITIES[i]);synthChord(state.selectedChord)});$("#nextChordBtn").addEventListener("click",()=>{let i=qIndex();if(i<0)i=0;i=(i+1)%QUALITIES.length;selectChord(state.root+QUALITIES[i]);synthChord(state.selectedChord)});
$("#keySelect").addEventListener("change",e=>{state.key=e.target.value;markDirty()});$("#statusSelect").addEventListener("change",e=>{state.status=e.target.value;markDirty()});
$("#saveBtn").addEventListener("click",()=>{state.notes[state.section]=$("#sectionNotes").value;const payload={song:$("#songSelect").value,key:state.key,status:state.status,strum:state.strum,strumNotes:state.strumNotes,sequences:state.sequences,notes:state.notes};try{localStorage.setItem("charango_current_record",JSON.stringify(payload));$("#saveStatus").textContent="Guardado en este navegador"}catch{$("#saveStatus").textContent="No se pudo guardar localmente"}});
async function loadSongs(){const select=$("#songSelect");let list=[];try{if(window.CancioneroDB?.listSongs)list=await window.CancioneroDB.listSongs()}catch{}if(!list.length)list=[{numero:"01",titulo:"Himno"},{numero:"02",titulo:"Por los Caminos"},{numero:"03",titulo:"Fiesta de mi Cautivo"}];select.replaceChildren();list.forEach(song=>{const o=document.createElement("option");o.value=song.id||song.numero||song.titulo;o.textContent=`${song.numero?song.numero+" · ":""}${song.titulo}`;select.append(o)})}
renderRootButtons();renderQualityButtons();renderSequence();renderUsedChords();renderChordDetail();loadSongs();
